Repository sedtrails/sedtrails, pull requests merged in 2025-08, with the labels that each got.

#264 Implement integrations test for physics plugins
  .github/workflows/pytest.yml
  pyproject.toml
  tests/transport_converter/plugins/test_physics_plugin.py
Labels: testing

#246 Compiled Soulsby physics plugin
  src/sedtrails/config/main.schema.json
  src/sedtrails/transport_converter/plugins/physics/soulsby.py
Labels: enhancement

#262 stuart's experiments with adding documentation
  docs/index.rst
  docs/introduction.rst
  docs/sourcecode/particle-tracer.rst
  docs/sourcecode/transport-converter.rst
  src/sedtrails/particle_tracer/orchestrator.py
Labels: documentation

#267 Particle seeding
  src/sedtrails/config/population.schema.json
  src/sedtrails/configuration_interface/configuration_controller.py
  src/sedtrails/configuration_interface/find.py
  src/sedtrails/exceptions/__init__.py
  src/sedtrails/exceptions/exceptions.py
  src/sedtrails/particle_tracer/particle.py
  src/sedtrails/particle_tracer/particle_seeder.py
  tests/particle_tracer/test_particle_seeder.py
Labels: enhancement

#281 started writing seeding documentation although things are changing
  docs/user/documentation_seeding.md
Labels: documentation

#282 final revisions of the diagrams
  diagrams/components-cache-app.puml
  diagrams/components-config-app.puml
  diagrams/components-connectivity-app.puml
  diagrams/components-converter-app.puml
  diagrams/components-data-app.puml
  diagrams/components-tracer-app.puml
  diagrams/containers.puml
  diagrams/context-system.puml
Labels: documentation

#280 Particle Population
  examples/seeder_example.py
  src/sedtrails/config/population.schema.json
  src/sedtrails/particle_tracer/__init__.py
  src/sedtrails/particle_tracer/particle_seeder.py
  src/sedtrails/particle_tracer/population.py
  tests/particle_tracer/test_particle_seeder.py
  tests/particle_tracer/test_population.py
Labels: bug, enhancement

#302 Fix timestep deviation check
  src/sedtrails/transport_converter/sedtrails_data.py
Labels: bug

#309 Visualization Dashboard
  examples/config.example.yaml
  src/sedtrails/config/visualization.schema.json
  src/sedtrails/pathway_visualizer/__init__.py
  src/sedtrails/pathway_visualizer/simulation_dashboard.py
  src/sedtrails/simulation.py
Labels: enhancement
