Repository sedtrails/sedtrails, pull requests merged in 2025-05, with the labels that each got.

#144 Fixes documentation and modules
  README.md
  src/sedtrails/exceptions/__init__.py
  src/sedtrails/exceptions/exceptions.py
Labels: bug

#153 Update README.md
  README.md
Labels: bug, documentation

#155 Fix typos in software diagrams and regenerate images
  diagrams/components-analysis-app.puml
  diagrams/components-cache-app.puml
  diagrams/components-config-app.puml
  diagrams/components-converter-app.puml
  diagrams/components-data-app.puml
  diagrams/components-tracer-app.puml
  diagrams/containers.puml
  docs/_static/img/architecture/SedtrailComponentsAnalysis.png
  docs/_static/img/architecture/SedtrailComponentsCache.png
  docs/_static/img/architecture/SedtrailComponentsConfigurationInterface.png
  docs/_static/img/architecture/SedtrailComponentsDataManagement.png
  docs/_static/img/architecture/SedtrailComponentsTracer.png
  docs/_static/img/architecture/SedtrailComponentsTransportConverter.png
  docs/_static/img/architecture/SedtrailContainer.png
  docs/_static/img/architecture/SedtrailContext.png
Labels: bug, documentation

#152 Add documentation for Lagrangian Particle Tracer Container
  docs/developer/architecture/software-diagrams.md
Labels: documentation

#161 Modify Time class in Particle class
  src/sedtrails/particle_tracer/particle.py
  tests/particle_tracer/test_particle.py
Labels: bug

#149 ST-147: configuration controller class
  src/sedtrails/configuration_interface/config_schema.json
  src/sedtrails/configuration_interface/configuration_controller.py
Labels: enhancement

#158 experiments with grain property classes and functions
  src/sedtrails/transport_converter/plugins/physics/library/dstar.py
  src/sedtrails/transport_converter/plugins/physics/library/shields_cr.py
  src/sedtrails/transport_converter/plugins/physics/library/shields_number.py
  src/sedtrails/transport_converter/plugins/physics/library/soulsby2011_p.py
  tests/converters/test_calculate_shields_cr.py
  tests/converters/test_dstar.py
  tests/converters/test_soulsby2011_p.py
Labels: enhancement, testing

#106 Progress on R function and one pytest on it
  src/sedtrails/transport_converter/plugins/physics/library/R_trial.py
  tests/transport_converter/plugins/physics/library/test_R_trial.py
Labels: help wanted

#171 Fixes to PR 107
  src/sedtrails/particle_tracer/particle-natasha.py
  src/sedtrails/transport_converter/plugins/physics/fluid.py
Labels: enhancement

#156 documentation (old and benchmark runs)
  docs/developer/benchmark_runs_matlab.md
  docs/user/jan2023/old_ch01_intro.md
  docs/user/jan2023/old_ch03_methods.md
  docs/user/jan2023/old_ch04_userManual.md
  docs/user/jan2023/old_overview.md
  docs/user/nov2023/old_sedtrailsPaperDraft.md
Labels: documentation

#157 Implement SedTRAILS format_converter module for NetCDF processing
  examples/reading_flowfields_example.py
  examples/visualization_utils.py
  src/sedtrails/particle_tracer/data_retriever.py
  src/sedtrails/transport_converter/format_converter.py
Labels: enhancement

#162 Seeding Tool
  examples/sedtrails_config.yaml
  src/sedtrails/particle_tracer/particle.py
  src/sedtrails/particle_tracer/particle_seeding.py
  src/sedtrails/particle_tracer/state_checker.py
  src/sedtrails/transport_converter/format_converter.py
  src/sedtrails/transport_converter/plugins/physics/library/dstar.py
  src/sedtrails/transport_converter/plugins/physics/library/soulsby2011_p.py
  tests/converters/test_soulsby2011_p.py
  tests/particle_tracer/test_particle.py
  tests/particle_tracer/test_particle_seeding.py
  tests/particle_tracer/test_time.py
Labels: enhancement
